### ISSUE TITLE
Add some examples HTML files

### ISSUE THREAD

**Issue by layflags** [ChristophP/web-react-components#10]
like the one on the test page, but in a separate folder `examples`. I think we can kick the test page then.

**Comment by ChristophP** [comment]
Good idea about adding examples. i think having the test page is still good though because then you can quickly check cross-browser.

**Comment by layflags** [comment]
We should automate x-browser testing, see [comment](https://github.com/ChristophP/web-react-components/issues/11#issuecomment-309306105)

**Comment by ChristophP** [comment]
Elm example added.
