### ISSUE TITLE
Add extra param to extends other Classes than HTMLElement

### ISSUE THREAD

**Issue by ChristophP** [ChristophP/web-react-components#13]
Sometimes it would be nice if it was possible to extend other elements like `HTMLButtonElement`. What do you think? Not super high priority but would be nice to have an optional parameter for `register` that defaults to `HTMLElement`.

**Comment by layflags** [comment]
Makes sense, but are there any other things to consider then? We should do some research first!

**Comment by ChristophP** [comment]
Doesn't make sense since we're only wrapping react components.
