### ISSUE TITLE
Use Webpack 3

### ISSUE THREAD

**Issue by layflags** [ChristophP/web-react-components#7]
That's the better option for libraries!

**Comment by ChristophP** [comment]
I've never really done anything with rollup, but heard that it is better for libraries.

**Comment by layflags** [comment]
We can keep Webpack for now and optimize the config (e.g. module resolution with Webpack instead of Babel, to save some bytes). Maybe later we can compare the bundle output of both.

**Comment by ChristophP** [comment]
Since webpack 3 now has `scope hoisting` this may not be necessary anymore.

**Comment by layflags** [comment]
True! Then we should use V3 ...
